site_name: Drush Docs
pages:
  - [index.md, 'Drush']
  - [usage.md, 'How to use']
  - [install.md, 'Installation']
  - [configuration.md, 'Configuration']
  - [support.md, 'Getting support']
  - [faq.md, 'FAQ']
  - [contributing.md, 'Contributing']
theme: readthedocs
site_author: ""
repo_url: https://github.com/drush-ops/drush