site_name: Drush Docs
pages:
  - [index.md, 'Home']
  - [install.md, 'Install']
  - [configuration.md, 'Configuration']
  - [support.md, 'Getting Support']
  - [faq.md, 'FAQ']
  - [contributing.md, 'Contributing']
theme: readthedocs
site_author: ""
repo_url: https://github.com/drush-ops/drush